// Code generated by "stringer -output enum_string.go -type=cond"; DO NOT EDIT.

package c99

import "fmt"

const _cond_name = "condZerocondIfOffcondIfOncondIfSkipmaxCond"

var _cond_index = [...]uint8{0, 8, 17, 25, 35, 42}

func (i cond) String() string {
	if i < 0 || i >= cond(len(_cond_index)-1) {
		return fmt.Sprintf("cond(%d)", i)
	}
	return _cond_name[_cond_index[i]:_cond_index[i+1]]
}
